/**
 * CasafariAlertsService - Service for Casafari Listing Alerts API
 * 
 * Documentation: https://docs.api.casafari.com/#tag/api-alerts
 * 
 * This service provides methods for:
 * - Managing alert feeds (create, update, delete, list)
 * - Retrieving alerts from feeds
 * - Searching and filtering alerts
 * - Managing alert statuses
 * 
 * Features:
 * - API authentication via Bearer token
 * - Comprehensive error handling
 * - Webhook support for real-time notifications
 * - Feed lifecycle management
 */

import type { CasafariConfig } from './types';
import type {
  CasafariAlertFeed,
  CasafariAlert,
  CasafariAlertsResponse,
  CasafariAlertFeedsResponse,
  CasafariAlertFeedResponse,
  CasafariCreateAlertFeedRequest,
  CasafariUpdateAlertFeedRequest,
  CasafariSearchAlertsRequest,
} from './types-alerts';
import { CasafariApiError } from './CasafariService';

/**
 * Casafari Alerts Service
 */
export class CasafariAlertsService {
  private apiKey: string;
  private baseUrl: string;
  private timeout: number;

  /**
   * Constructor
   * 
   * @param config - Service configuration
   */
  constructor(config: CasafariConfig) {
    this.apiKey = config.apiKey;
    this.baseUrl = config.baseUrl || 'https://api.casafari.com';
    this.timeout = config.timeout || 30000;
  }

  /**
   * List all alert feeds
   * 
   * Retrieves all alert feeds for the authenticated user.
   * 
   * @param page - Page number for pagination (default: 1)
   * @param limit - Items per page (default: 20)
   * @returns List of alert feeds
   * 
   * @example
   * ```typescript
   * const feeds = await service.listFeeds(1, 50);
   * console.log(`Found ${feeds.pagination.total} feeds`);
   * feeds.data.forEach(feed => {
   *   console.log(`${feed.name}: ${feed.alertsCount} alerts`);
   * });
   * ```
   */
  async listFeeds(
    page: number = 1,
    limit: number = 20
  ): Promise<CasafariAlertFeedsResponse> {
    const url = `${this.baseUrl}/api/v1/listing-alerts/feeds?page=${page}&limit=${limit}`;

    try {
      const response = await this.makeRequest<CasafariAlertFeedsResponse>(url, 'GET');
      return response;
    } catch (error) {
      console.error('[CasafariAlertsService] Error listing feeds:', error);
      throw error;
    }
  }

  /**
   * Create a new alert feed
   * 
   * Creates a new alert feed with specified filters and notification settings.
   * 
   * @param request - Feed configuration
   * @returns Created feed
   * 
   * @example
   * ```typescript
   * const feed = await service.createFeed({
   *   name: 'Apartamentos T2 em Lisboa',
   *   description: 'Apartamentos de 2 quartos em Lisboa até €300k',
   *   filters: {
   *     municipality: ['Lisboa'],
   *     propertyType: ['apartment'],
   *     transactionType: 'sale',
   *     minBedrooms: 2,
   *     maxBedrooms: 2,
   *     maxPrice: 300000
   *   },
   *   frequency: 'realtime',
   *   email: 'consultant@example.com',
   *   status: 'active'
   * });
   * console.log(`Feed created with ID: ${feed.id}`);
   * ```
   */
  async createFeed(
    request: CasafariCreateAlertFeedRequest
  ): Promise<CasafariAlertFeed> {
    const url = `${this.baseUrl}/api/v1/listing-alerts/feeds`;

    try {
      const response = await this.makeRequest<CasafariAlertFeedResponse>(
        url,
        'POST',
        request
      );
      return response.data;
    } catch (error) {
      console.error('[CasafariAlertsService] Error creating feed:', error);
      throw error;
    }
  }

  /**
   * Get alerts from a specific feed
   * 
   * Retrieves all alerts generated by a specific feed.
   * 
   * @param feedId - Feed identifier
   * @param page - Page number for pagination (default: 1)
   * @param limit - Items per page (default: 50)
   * @param status - Filter by alert status (optional)
   * @returns List of alerts
   * 
   * @example
   * ```typescript
   * const alerts = await service.getAlertsByFeed('feed-123', 1, 50, 'unread');
   * console.log(`${alerts.summary?.unreadCount} unread alerts`);
   * 
   * alerts.data.forEach(alert => {
   *   console.log(`${alert.subtype}: ${alert.property.title}`);
   *   console.log(`Price: €${alert.property.price.current}`);
   * });
   * ```
   */
  async getAlertsByFeed(
    feedId: string,
    page: number = 1,
    limit: number = 50,
    status?: 'unread' | 'read' | 'archived' | 'dismissed'
  ): Promise<CasafariAlertsResponse> {
    let url = `${this.baseUrl}/api/v1/listing-alerts/feeds/${feedId}?page=${page}&limit=${limit}`;
    
    if (status) {
      url += `&status=${status}`;
    }

    try {
      const response = await this.makeRequest<CasafariAlertsResponse>(url, 'GET');
      return response;
    } catch (error) {
      console.error('[CasafariAlertsService] Error getting alerts by feed:', error);
      throw error;
    }
  }

  /**
   * Delete an alert feed
   * 
   * Permanently deletes an alert feed and all its associated alerts.
   * 
   * @param feedId - Feed identifier
   * @returns Success confirmation
   * 
   * @example
   * ```typescript
   * await service.deleteFeed('feed-123');
   * console.log('Feed deleted successfully');
   * ```
   */
  async deleteFeed(feedId: string): Promise<{ success: boolean; message: string }> {
    const url = `${this.baseUrl}/api/v1/listing-alerts/feeds/${feedId}`;

    try {
      await this.makeRequest<void>(url, 'DELETE');
      return {
        success: true,
        message: `Feed ${feedId} deleted successfully`,
      };
    } catch (error) {
      console.error('[CasafariAlertsService] Error deleting feed:', error);
      throw error;
    }
  }

  /**
   * Search alerts across all feeds
   * 
   * Search and filter alerts across all feeds with various criteria.
   * 
   * @param request - Search filters
   * @returns Filtered alerts
   * 
   * @example
   * ```typescript
   * const alerts = await service.searchAlerts({
   *   status: ['unread'],
   *   subtypes: ['new_listing', 'price_reduction'],
   *   propertyType: ['apartment'],
   *   municipality: ['Lisboa', 'Porto'],
   *   maxPrice: 350000,
   *   createdAfter: '2024-01-01',
   *   sortBy: 'createdAt',
   *   sortOrder: 'desc',
   *   limit: 100
   * });
   * ```
   */
  async searchAlerts(
    request: CasafariSearchAlertsRequest
  ): Promise<CasafariAlertsResponse> {
    const url = `${this.baseUrl}/api/v1/listing-alerts/search`;

    try {
      const response = await this.makeRequest<CasafariAlertsResponse>(
        url,
        'POST',
        request
      );
      return response;
    } catch (error) {
      console.error('[CasafariAlertsService] Error searching alerts:', error);
      throw error;
    }
  }

  /**
   * Update an alert feed
   * 
   * Updates an existing alert feed's configuration.
   * 
   * @param feedId - Feed identifier
   * @param request - Updated feed configuration
   * @returns Updated feed
   * 
   * @example
   * ```typescript
   * const updatedFeed = await service.updateFeed('feed-123', {
   *   filters: {
   *     ...existingFilters,
   *     maxPrice: 350000  // Increase max price
   *   },
   *   status: 'active'
   * });
   * ```
   */
  async updateFeed(
    feedId: string,
    request: CasafariUpdateAlertFeedRequest
  ): Promise<CasafariAlertFeed> {
    const url = `${this.baseUrl}/api/v1/listing-alerts/feeds/${feedId}/update`;

    try {
      const response = await this.makeRequest<CasafariAlertFeedResponse>(
        url,
        'PUT',
        request
      );
      return response.data;
    } catch (error) {
      console.error('[CasafariAlertsService] Error updating feed:', error);
      throw error;
    }
  }

  /**
   * Get a specific feed by ID
   * 
   * Retrieves detailed information about a specific feed.
   * 
   * @param feedId - Feed identifier
   * @returns Feed details
   * 
   * @example
   * ```typescript
   * const feed = await service.getFeed('feed-123');
   * console.log(`Feed: ${feed.name}`);
   * console.log(`Alerts generated: ${feed.alertsCount}`);
   * console.log(`Status: ${feed.status}`);
   * ```
   */
  async getFeed(feedId: string): Promise<CasafariAlertFeed> {
    const url = `${this.baseUrl}/api/v1/listing-alerts/feeds/${feedId}`;

    try {
      const response = await this.makeRequest<CasafariAlertFeedResponse>(url, 'GET');
      return response.data;
    } catch (error) {
      console.error('[CasafariAlertsService] Error getting feed:', error);
      throw error;
    }
  }

  /**
   * Mark alert as read
   * 
   * Updates alert status to 'read'.
   * 
   * @param alertId - Alert identifier
   * @returns Updated alert
   * 
   * @example
   * ```typescript
   * await service.markAlertAsRead('alert-456');
   * ```
   */
  async markAlertAsRead(alertId: string): Promise<CasafariAlert> {
    return this.updateAlertStatus(alertId, 'read');
  }

  /**
   * Mark alert as archived
   * 
   * Updates alert status to 'archived'.
   * 
   * @param alertId - Alert identifier
   * @returns Updated alert
   */
  async markAlertAsArchived(alertId: string): Promise<CasafariAlert> {
    return this.updateAlertStatus(alertId, 'archived');
  }

  /**
   * Mark alert as dismissed
   * 
   * Updates alert status to 'dismissed'.
   * 
   * @param alertId - Alert identifier
   * @returns Updated alert
   */
  async markAlertAsDismissed(alertId: string): Promise<CasafariAlert> {
    return this.updateAlertStatus(alertId, 'dismissed');
  }

  /**
   * Pause a feed
   * 
   * Pauses alert generation for a feed without deleting it.
   * 
   * @param feedId - Feed identifier
   * @returns Updated feed
   * 
   * @example
   * ```typescript
   * await service.pauseFeed('feed-123');
   * console.log('Feed paused - no new alerts will be generated');
   * ```
   */
  async pauseFeed(feedId: string): Promise<CasafariAlertFeed> {
    return this.updateFeed(feedId, { status: 'paused' });
  }

  /**
   * Resume a paused feed
   * 
   * Reactivates a paused feed.
   * 
   * @param feedId - Feed identifier
   * @returns Updated feed
   */
  async resumeFeed(feedId: string): Promise<CasafariAlertFeed> {
    return this.updateFeed(feedId, { status: 'active' });
  }

  /**
   * Get unread alerts count
   * 
   * Retrieves the total number of unread alerts across all feeds.
   * 
   * @returns Unread count
   * 
   * @example
   * ```typescript
   * const count = await service.getUnreadCount();
   * console.log(`You have ${count} unread alerts`);
   * ```
   */
  async getUnreadCount(): Promise<number> {
    try {
      const response = await this.searchAlerts({
        status: ['unread'],
        limit: 1,
      });
      return response.summary?.unreadCount || response.pagination.total;
    } catch (error) {
      console.error('[CasafariAlertsService] Error getting unread count:', error);
      throw error;
    }
  }

  /**
   * Update alert status
   * @private
   */
  private async updateAlertStatus(
    alertId: string,
    status: 'read' | 'archived' | 'dismissed'
  ): Promise<CasafariAlert> {
    const url = `${this.baseUrl}/api/v1/listing-alerts/alerts/${alertId}`;

    try {
      const response = await this.makeRequest<{ data: CasafariAlert }>(
        url,
        'PUT',
        { status }
      );
      return response.data;
    } catch (error) {
      console.error('[CasafariAlertsService] Error updating alert status:', error);
      throw error;
    }
  }

  /**
   * Make HTTP request to Casafari API
   * @private
   */
  private async makeRequest<T>(
    url: string,
    method: 'GET' | 'POST' | 'PUT' | 'DELETE' = 'GET',
    body?: any
  ): Promise<T> {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this.timeout);

    try {
      const response = await fetch(url, {
        method,
        headers: {
          'Authorization': `Bearer ${this.apiKey}`,
          'Content-Type': 'application/json',
          'Accept': 'application/json',
        },
        body: body ? JSON.stringify(body) : undefined,
        signal: controller.signal,
      });

      clearTimeout(timeoutId);

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new CasafariApiError(
          errorData.error?.message || `HTTP ${response.status}: ${response.statusText}`,
          response.status,
          errorData.error?.code,
          errorData.error?.details
        );
      }

      // Handle 204 No Content for DELETE
      if (response.status === 204) {
        return {} as T;
      }

      return await response.json();
    } catch (error) {
      clearTimeout(timeoutId);

      if (error instanceof CasafariApiError) {
        throw error;
      }

      if ((error as Error).name === 'AbortError') {
        throw new CasafariApiError('Request timeout', 408);
      }

      throw new CasafariApiError(
        `Network error: ${(error as Error).message}`,
        0
      );
    }
  }
}

/**
 * Factory function to create CasafariAlertsService instance
 * 
 * @param config - Service configuration (optional, uses env vars if not provided)
 * @returns CasafariAlertsService instance
 * 
 * @example
 * ```typescript
 * // Using environment variable CASAFARI_API_KEY
 * const service = createCasafariAlertsService();
 * 
 * // With explicit configuration
 * const service = createCasafariAlertsService({
 *   apiKey: 'your-api-key',
 *   baseUrl: 'https://api.casafari.com',
 *   timeout: 30000
 * });
 * ```
 */
export function createCasafariAlertsService(
  config?: Partial<CasafariConfig>
): CasafariAlertsService {
  const apiKey = config?.apiKey || process.env.CASAFARI_API_KEY || '';

  if (!apiKey) {
    throw new Error(
      'Casafari API key is required. Set CASAFARI_API_KEY environment variable or provide in config.'
    );
  }

  return new CasafariAlertsService({
    apiKey,
    baseUrl: config?.baseUrl,
    timeout: config?.timeout,
  });
}
